import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from 'geist/font/sans';

import { ThemeProvider } from "@/components/ThemeProvider"
import Navbar from '@/components/Navbar';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
      <html lang="en" className={GeistSans.className}>
      <head>
        <link rel="stylesheet" href="https://fa.xdws.work/latest" />
        <link rel="icon" href="/assets/favicon.png" sizes="any" />
      </head>
      <body
      >
      <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
      >
          {children}
      </ThemeProvider>
      </body>
      </html>
  );
}
